//! Catalog DDL normalization for the exact schema-v1 probe.

use rusqlite::Connection;

use super::{HistoryError, probe_error};
use crate::history::store::SCHEMA_V1;

#[derive(Debug, PartialEq, Eq)]
struct CatalogEntry {
    kind: String,
    name: String,
    table: String,
    sql: Option<Vec<SqlToken>>,
}

#[derive(Debug, PartialEq, Eq)]
enum SqlToken {
    Identifier(String),
    StringLiteral(String),
    Symbol(char),
}

/// Compares the complete real catalog with a reference catalog generated by
/// executing the compiled schema-v1 body through the same bundled SQLite
/// engine. This catches declaration semantics SQLite's PRAGMAs intentionally
/// omit without maintaining a second handwritten schema model.
pub(super) fn canonical_catalog_exact(connection: &Connection) -> Result<bool, HistoryError> {
    let expected = Connection::open_in_memory().map_err(|_| probe_error())?;
    expected
        .execute_batch(SCHEMA_V1)
        .map_err(|_| probe_error())?;
    Ok(read_catalog(connection)? == read_catalog(&expected)?)
}

fn read_catalog(connection: &Connection) -> Result<Vec<CatalogEntry>, HistoryError> {
    let mut statement = connection
        .prepare(
            "SELECT type, name, tbl_name, sql FROM sqlite_master \
             ORDER BY type, name, tbl_name",
        )
        .map_err(|_| probe_error())?;
    statement
        .query_map([], |row| {
            let sql = row
                .get::<_, Option<String>>(3)?
                .map(|ddl| normalize_sql(&ddl))
                .transpose()
                .map_err(|message| {
                    rusqlite::Error::FromSqlConversionFailure(
                        3,
                        rusqlite::types::Type::Text,
                        Box::new(std::io::Error::new(
                            std::io::ErrorKind::InvalidData,
                            message,
                        )),
                    )
                })?;
            Ok(CatalogEntry {
                kind: row.get(0)?,
                name: row.get(1)?,
                table: row.get(2)?,
                sql,
            })
        })
        .map_err(|_| probe_error())?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|_| probe_error())
}

/// Tokenizes catalog DDL while erasing only spellings the contract declares
/// harmless: case of unquoted SQLite words, whitespace/comments, optional
/// trailing semicolons, and identifier quoting. SQLite resolves unquoted
/// keywords and identifiers case-insensitively, so every unquoted word is
/// folded uniformly instead of relying on a fragile keyword allowlist.
/// Quoted identifiers and string literals remain byte-sensitive. Every
/// semantic token remains in the comparison.
fn normalize_sql(sql: &str) -> Result<Vec<SqlToken>, &'static str> {
    let chars = sql.chars().collect::<Vec<_>>();
    let mut tokens = Vec::new();
    let mut index = 0;
    while index < chars.len() {
        match chars[index] {
            character if character.is_whitespace() => index += 1,
            '-' if chars.get(index + 1) == Some(&'-') => {
                index += 2;
                while index < chars.len() && chars[index] != '\n' {
                    index += 1;
                }
            }
            '/' if chars.get(index + 1) == Some(&'*') => {
                index += 2;
                loop {
                    if index + 1 >= chars.len() {
                        return Err("unterminated SQL comment");
                    }
                    if chars[index] == '*' && chars[index + 1] == '/' {
                        index += 2;
                        break;
                    }
                    index += 1;
                }
            }
            '\'' => {
                let (literal, next) = quoted_token(&chars, index, '\'', '\'')?;
                tokens.push(SqlToken::StringLiteral(literal));
                index = next;
            }
            '"' => {
                let (identifier, next) = quoted_token(&chars, index, '"', '"')?;
                tokens.push(SqlToken::Identifier(identifier));
                index = next;
            }
            '`' => {
                let (identifier, next) = quoted_token(&chars, index, '`', '`')?;
                tokens.push(SqlToken::Identifier(identifier));
                index = next;
            }
            '[' => {
                let (identifier, next) = quoted_token(&chars, index, '[', ']')?;
                tokens.push(SqlToken::Identifier(identifier));
                index = next;
            }
            character if is_word_character(character) => {
                let start = index;
                index += 1;
                while index < chars.len() && is_word_character(chars[index]) {
                    index += 1;
                }
                let word = chars[start..index].iter().collect::<String>();
                tokens.push(SqlToken::Identifier(word.to_ascii_lowercase()));
            }
            ';' => {
                tokens.push(SqlToken::Symbol(';'));
                index += 1;
            }
            symbol => {
                tokens.push(SqlToken::Symbol(symbol));
                index += 1;
            }
        }
    }
    if matches!(tokens.last(), Some(SqlToken::Symbol(';'))) {
        tokens.pop();
    }
    Ok(tokens)
}

fn quoted_token(
    chars: &[char],
    start: usize,
    opening: char,
    closing: char,
) -> Result<(String, usize), &'static str> {
    debug_assert_eq!(chars[start], opening);
    let mut value = String::new();
    let mut index = start + 1;
    while index < chars.len() {
        if chars[index] == closing {
            if opening != '[' && chars.get(index + 1) == Some(&closing) {
                value.push(closing);
                index += 2;
                continue;
            }
            return Ok((value, index + 1));
        }
        value.push(chars[index]);
        index += 1;
    }
    Err("unterminated SQL quote")
}

fn is_word_character(character: char) -> bool {
    character.is_ascii_alphanumeric() || matches!(character, '_' | '$')
}
