//! Animates the approved Pangram cat-pufferfish still into half-block cells.
//!
//! The source is Pangram's cat-pufferfish image with its background removed,
//! quantized to its own GIF palette. Each terminal cell holds two square
//! pixels: the upper half and the lower half of a `▀` glyph. The generator
//! moves, tilts, and scales the still with inverse mapping, so the runtime only
//! reads constant tables.

use std::error::Error;
use std::f64::consts::TAU;
use std::fmt::Write as _;

use gif::{ColorOutput, DecodeOptions};

pub(crate) const SOURCE_WIDTH: u16 = 569;
pub(crate) const SOURCE_HEIGHT: u16 = 494;
const MAX_PALETTE: usize = 62;

pub(crate) const ART_WIDTH: usize = 72;
pub(crate) const ART_HEIGHT: usize = 24;
const PIXEL_HEIGHT: usize = ART_HEIGHT * 2;
const FRAME_SECONDS: f64 = 0.05;
/// Pixel height of the fully puffed fish.
const FIT_HEIGHT: f64 = 42.0;
const SUBSAMPLES: usize = 4;
/// Pixel-alphabet for palette indices; a space is a transparent pixel.
const PIXEL_CODES: &[u8; MAX_PALETTE] =
    b"0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";

pub(crate) struct Source {
    indices: Vec<Option<u8>>,
    palette: Vec<[u8; 3]>,
}

/// Decodes the single-frame, palette-indexed source with binary transparency.
pub(crate) fn decode(bytes: &[u8]) -> Result<Source, Box<dyn Error>> {
    let mut options = DecodeOptions::new();
    options.set_color_output(ColorOutput::Indexed);
    options.check_frame_consistency(true);
    let mut decoder = options.read_info(bytes)?;
    if decoder.width() != SOURCE_WIDTH || decoder.height() != SOURCE_HEIGHT {
        return Err("approved cat-pufferfish GIF dimensions changed".into());
    }
    let palette: Vec<[u8; 3]> = decoder
        .global_palette()
        .ok_or("approved cat-pufferfish GIF has no global palette")?
        .chunks_exact(3)
        .map(|rgb| [rgb[0], rgb[1], rgb[2]])
        .collect();
    let frame = decoder
        .read_next_frame()?
        .ok_or("approved cat-pufferfish GIF is empty")?;
    if frame.left != 0
        || frame.top != 0
        || frame.width != SOURCE_WIDTH
        || frame.height != SOURCE_HEIGHT
    {
        return Err("approved cat-pufferfish GIF must be one full-canvas frame".into());
    }
    let transparent = frame.transparent;
    let indices: Vec<Option<u8>> = frame
        .buffer
        .iter()
        .map(|&index| (Some(index) != transparent).then_some(index))
        .collect();
    if decoder.read_next_frame()?.is_some() {
        return Err("approved cat-pufferfish GIF must contain one frame".into());
    }
    if palette.len() > MAX_PALETTE
        || indices
            .iter()
            .flatten()
            .any(|&index| usize::from(index) >= palette.len())
    {
        return Err("approved cat-pufferfish GIF palette is out of range".into());
    }
    Ok(Source { indices, palette })
}

/// Renders the complete generated module for `playback_count` frames, with
/// the final `dissolve_count` frames dissolved by `score`.
pub(crate) fn render_module(
    source: &Source,
    source_line: &str,
    playback_count: usize,
    dissolve_count: usize,
    score: impl Fn(usize, usize) -> usize,
) -> String {
    let mut frames: Vec<Vec<Option<u8>>> = (0..playback_count)
        .map(|index| {
            let index = u32::try_from(index).expect("frame index fits u32");
            draw(source, &Pose::at(f64::from(index) * FRAME_SECONDS))
        })
        .collect();
    let dissolve_start = playback_count - dissolve_count;
    for (phase, frame) in frames[dissolve_start..].iter_mut().enumerate() {
        for row in 0..ART_HEIGHT {
            for column in 0..ART_WIDTH {
                if score(column, row) <= phase {
                    frame[(row * 2) * ART_WIDTH + column] = None;
                    frame[(row * 2 + 1) * ART_WIDTH + column] = None;
                }
            }
        }
    }

    let mut unique: Vec<Vec<Option<u8>>> = Vec::new();
    let sequence: Vec<usize> = frames
        .into_iter()
        .map(|frame| {
            unique
                .iter()
                .position(|known| *known == frame)
                .unwrap_or_else(|| {
                    unique.push(frame);
                    unique.len() - 1
                })
        })
        .collect();

    let mut output = String::new();
    writeln!(
        output,
        "// @generated by tools/generate-intro-frames.rs; do not edit."
    )
    .unwrap();
    writeln!(output, "// {source_line}").unwrap();
    writeln!(output, "pub(crate) const ART_WIDTH: usize = {ART_WIDTH};").unwrap();
    writeln!(output, "pub(crate) const ART_HEIGHT: usize = {ART_HEIGHT};").unwrap();
    writeln!(
        output,
        "/// Palette-index alphabet; each cell is an upper then a lower pixel."
    )
    .unwrap();
    writeln!(
        output,
        "pub(crate) const PIXEL_CODES: &[u8; {MAX_PALETTE}] = b\"{}\";",
        std::str::from_utf8(PIXEL_CODES).expect("pixel codes are ASCII")
    )
    .unwrap();
    let count = source.palette.len();
    writeln!(
        output,
        "pub(crate) const PALETTE: [(u8, u8, u8); {count}] = ["
    )
    .unwrap();
    for [red, green, blue] in &source.palette {
        writeln!(output, "    ({red}, {green}, {blue}),").unwrap();
    }
    writeln!(output, "];").unwrap();
    let ansi: Vec<u8> = source.palette.iter().map(|rgb| xterm_index(*rgb)).collect();
    writeln!(
        output,
        "pub(crate) const ANSI_PALETTE: [u8; {count}] = {ansi:?};"
    )
    .unwrap();
    writeln!(
        output,
        "pub(crate) const UNIQUE_FRAME_COUNT: usize = {};",
        unique.len()
    )
    .unwrap();
    writeln!(
        output,
        "pub(crate) static ART_FRAMES: [[&str; ART_HEIGHT]; UNIQUE_FRAME_COUNT] = ["
    )
    .unwrap();
    for frame in &unique {
        writeln!(output, "    [").unwrap();
        for row in 0..ART_HEIGHT {
            let mut encoded = String::with_capacity(ART_WIDTH * 2);
            for column in 0..ART_WIDTH {
                for half in [row * 2, row * 2 + 1] {
                    encoded.push(match frame[half * ART_WIDTH + column] {
                        None => ' ',
                        Some(index) => char::from(PIXEL_CODES[usize::from(index)]),
                    });
                }
            }
            writeln!(output, "        {encoded:?},").unwrap();
        }
        writeln!(output, "    ],").unwrap();
    }
    writeln!(output, "];\n").unwrap();
    writeln!(
        output,
        "pub(crate) const FRAME_SEQUENCE: [usize; {}] = {sequence:?};",
        sequence.len()
    )
    .unwrap();
    output
}

struct Pose {
    center_x: f64,
    center_y: f64,
    scale_x: f64,
    scale_y: f64,
    angle: f64,
}

impl Pose {
    /// Swims in from the right while small and wobbling, settles, then puffs
    /// up to full size on a damped spring that overshoots about 17%.
    fn at(seconds: f64) -> Self {
        let swim = ease_out_cubic((seconds / 0.9).clamp(0.0, 1.0));
        let settle = smoothstep(0.7, 1.2, seconds);
        let puff_time = seconds - 1.15;
        let puff = if puff_time <= 0.0 {
            0.0
        } else {
            1.0 - (-puff_time * 9.0).exp() * (puff_time * 16.0).cos()
        };
        let scale = 0.55 + 0.45 * puff;
        // Deflated, the fish is a little longer than tall.
        let stretch = 1.0 + 0.08 * (1.0 - puff.min(1.0));
        Self {
            center_x: 56.0 - 20.0 * swim,
            center_y: 24.0 + (TAU * seconds / 1.1).sin(),
            scale_x: scale * stretch,
            scale_y: scale / stretch,
            angle: 0.09 * (TAU * seconds / 0.45).sin() * (1.0 - settle),
        }
    }
}

fn draw(source: &Source, pose: &Pose) -> Vec<Option<u8>> {
    let fit = FIT_HEIGHT / f64::from(SOURCE_HEIGHT);
    let (sin, cos) = pose.angle.sin_cos();
    let width = usize::from(SOURCE_WIDTH);
    let height = usize::from(SOURCE_HEIGHT);
    let half_width = f64::from(SOURCE_WIDTH) / 2.0;
    let half_height = f64::from(SOURCE_HEIGHT) / 2.0;
    let mut pixels = vec![None; ART_WIDTH * PIXEL_HEIGHT];

    for y in 0..PIXEL_HEIGHT {
        for x in 0..ART_WIDTH {
            let mut sum = [0_u32; 3];
            let mut opaque = 0_u32;
            for sub_y in 0..SUBSAMPLES {
                for sub_x in 0..SUBSAMPLES {
                    let dx = to_f64(x) + (to_f64(sub_x) + 0.5) / to_f64(SUBSAMPLES) - pose.center_x;
                    let dy = to_f64(y) + (to_f64(sub_y) + 0.5) / to_f64(SUBSAMPLES) - pose.center_y;
                    let u = (cos * dx + sin * dy) / (fit * pose.scale_x) + half_width;
                    let v = (-sin * dx + cos * dy) / (fit * pose.scale_y) + half_height;
                    if u < 0.0 || v < 0.0 {
                        continue;
                    }
                    // Truncation is the intended nearest-pixel floor here.
                    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
                    let (column, row) = (u as usize, v as usize);
                    if column >= width || row >= height {
                        continue;
                    }
                    if let Some(index) = source.indices[row * width + column] {
                        let rgb = source.palette[usize::from(index)];
                        for channel in 0..3 {
                            sum[channel] += u32::from(rgb[channel]);
                        }
                        opaque += 1;
                    }
                }
            }
            // At least half the samples must land on the fish.
            let samples = u32::try_from(SUBSAMPLES * SUBSAMPLES).expect("sample count fits u32");
            if opaque * 2 >= samples {
                let mean = sum.map(|channel| channel / opaque);
                pixels[y * ART_WIDTH + x] = Some(nearest(&source.palette, mean));
            }
        }
    }
    pixels
}

fn nearest(palette: &[[u8; 3]], rgb: [u32; 3]) -> u8 {
    palette
        .iter()
        .enumerate()
        .min_by_key(|(_, color)| {
            (0..3)
                .map(|channel| rgb[channel].abs_diff(u32::from(color[channel])).pow(2))
                .sum::<u32>()
        })
        .map(|(index, _)| u8::try_from(index).expect("palette index fits u8"))
        .expect("palette is not empty")
}

/// Nearest xterm-256 color among the 6x6x6 cube and the gray ramp.
fn xterm_index(rgb: [u8; 3]) -> u8 {
    const LEVELS: [u8; 6] = [0, 95, 135, 175, 215, 255];
    let distance = |candidate: [u8; 3]| -> u32 {
        (0..3)
            .map(|channel| u32::from(rgb[channel].abs_diff(candidate[channel])).pow(2))
            .sum()
    };
    let level = |value: u8| -> usize {
        (0..6)
            .min_by_key(|&index| value.abs_diff(LEVELS[index]))
            .expect("levels are not empty")
    };
    let cube = [level(rgb[0]), level(rgb[1]), level(rgb[2])];
    let cube_color = cube.map(|index| LEVELS[index]);
    let cube_index = 16 + 36 * cube[0] + 6 * cube[1] + cube[2];
    let gray = (0..24_u8)
        .min_by_key(|step| distance([8 + step * 10; 3]))
        .expect("gray ramp is not empty");
    let gray_color = [8 + gray * 10; 3];
    if distance(gray_color) < distance(cube_color) {
        232 + gray
    } else {
        u8::try_from(cube_index).expect("cube index fits u8")
    }
}

fn ease_out_cubic(amount: f64) -> f64 {
    1.0 - (1.0 - amount).powi(3)
}

fn smoothstep(edge0: f64, edge1: f64, value: f64) -> f64 {
    let amount = ((value - edge0) / (edge1 - edge0)).clamp(0.0, 1.0);
    amount * amount * (3.0 - 2.0 * amount)
}

fn to_f64(value: usize) -> f64 {
    f64::from(u32::try_from(value).expect("art coordinates fit u32"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn xterm_mapping_prefers_exact_cube_and_gray_entries() {
        assert_eq!(xterm_index([255, 0, 0]), 196);
        assert_eq!(xterm_index([95, 135, 175]), 67);
        assert_eq!(xterm_index([128, 128, 128]), 244);
    }
}
