//! Deterministic generated artifacts owned by the Rust contract types.
//!
//! The committed files are outputs. This module never reads them while
//! generating, so the drift test cannot pass by copying a stale seed contract.

use std::collections::BTreeMap;
use std::fs;
use std::io::Write as _;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use schemars::JsonSchema;
use schemars::generate::SchemaSettings;
use serde_json::{Map, Value, json};
use thiserror::Error;

use crate::cli::{FULL_GRAMMAR, runtime_command};
use crate::domain::{
    Analysis, AnalysisPage, BulkCollection, BulkItem, BulkPage, Check, CheckStatus, OrderedChecks,
    SubmissionOutcomeUnknownDetails,
};
use crate::output::{
    CanonicalError, EnvelopeMeta, ErrorCode, ExitCode, ResolvedCommand,
    SUBMISSION_OUTCOME_UNKNOWN_RECOVERY_MESSAGE,
};

mod schema_types;

const CONTRACT_OWNER: &str = "rust:microck_pangram_cli::contracts";
const DRAFT_2020_12: &str = "https://json-schema.org/draft/2020-12/schema";

/// One path and its canonical generated bytes, relative to the repository root.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedArtifact {
    pub path: String,
    pub bytes: Vec<u8>,
}

/// Contract generation failed before every artifact could be produced.
#[derive(Debug, Error)]
pub enum ContractGenerationError {
    #[error("failed to serialize a generated contract: {0}")]
    Serialize(#[from] serde_json::Error),
    #[error("failed to write generated contract {path}: {source}")]
    Write {
        path: String,
        #[source]
        source: std::io::Error,
    },
}

/// Produces every committed contract without consulting the committed output.
pub fn generated_artifacts() -> Result<Vec<GeneratedArtifact>, ContractGenerationError> {
    let mut help_command = runtime_command();
    let help = format!("{}\n", help_command.render_help().to_string().trim_end());

    Ok(vec![
        json_artifact("contracts/config.schema.json", config_schema())?,
        json_artifact(
            "contracts/install-receipt.schema.json",
            install_receipt_schema(),
        )?,
        json_artifact(
            "contracts/manifest-signature.schema.json",
            manifest_signature_schema(),
        )?,
        json_artifact("contracts/output.schema.json", output_schema())?,
        json_artifact("contracts/tui-state.schema.json", tui_state_schema())?,
        json_artifact(
            "contracts/update-manifest.schema.json",
            update_manifest_schema(),
        )?,
        json_artifact("contracts/update-state.schema.json", update_state_schema())?,
        GeneratedArtifact {
            path: "generated/cli-help.txt".into(),
            bytes: help.into_bytes(),
        },
        compact_json_artifact("generated/cli-reference.json", cli_reference())?,
        json_artifact("generated/error-reference.json", error_reference())?,
    ])
}

/// Writes the canonical artifacts below `root`.
pub fn write_generated_artifacts(root: &Path) -> Result<(), ContractGenerationError> {
    let artifacts = generated_artifacts()?;
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let mut staged: Vec<(PathBuf, PathBuf)> = Vec::with_capacity(artifacts.len());

    // Complete every fallible content write before replacing any committed
    // artifact. Cross-directory replacement cannot be one atomic operation,
    // but ordinary staging failures leave the previous set intact.
    for (index, artifact) in artifacts.iter().enumerate() {
        let path = root.join(&artifact.path);
        let parent = path.parent().expect("generated artifacts have a parent");
        let file_name = path
            .file_name()
            .and_then(|name| name.to_str())
            .expect("generated artifact names are UTF-8");
        let temporary = parent.join(format!(
            ".{file_name}.{}-{nonce}-{index}.tmp",
            std::process::id()
        ));
        let stage_result = (|| -> std::io::Result<()> {
            fs::create_dir_all(parent)?;
            let mut file = fs::OpenOptions::new()
                .write(true)
                .create_new(true)
                .open(&temporary)?;
            file.write_all(&artifact.bytes)?;
            file.sync_all()
        })();

        if let Err(source) = stage_result {
            cleanup_staged(&staged);
            let _ = fs::remove_file(&temporary);
            return Err(ContractGenerationError::Write {
                path: path.display().to_string(),
                source,
            });
        }
        staged.push((temporary, path));
    }

    for index in 0..staged.len() {
        let (temporary, path) = &staged[index];
        if let Err(source) = fs::rename(temporary, path) {
            cleanup_staged(&staged[index..]);
            return Err(ContractGenerationError::Write {
                path: path.display().to_string(),
                source,
            });
        }
    }
    Ok(())
}

fn cleanup_staged(staged: &[(PathBuf, PathBuf)]) {
    for (temporary, _) in staged {
        let _ = fs::remove_file(temporary);
    }
}

fn json_artifact(path: &str, value: Value) -> Result<GeneratedArtifact, ContractGenerationError> {
    let mut bytes = serde_json::to_vec_pretty(&value)?;
    bytes.push(b'\n');
    Ok(GeneratedArtifact {
        path: path.into(),
        bytes,
    })
}

fn compact_json_artifact(
    path: &str,
    value: Value,
) -> Result<GeneratedArtifact, ContractGenerationError> {
    let mut bytes = serde_json::to_vec(&value)?;
    bytes.push(b'\n');
    Ok(GeneratedArtifact {
        path: path.into(),
        bytes,
    })
}

fn rust_schema<T: JsonSchema>() -> Value {
    let schema = SchemaSettings::draft2020_12()
        .into_generator()
        .into_root_schema_for::<T>();
    serde_json::to_value(schema).expect("Schemars schemas always serialize")
}

fn root_schema<T: JsonSchema>(id: &str, title: &str) -> Value {
    let mut schema = rust_schema::<T>();
    strip_optional_nulls(&mut schema);
    let root = object_mut(&mut schema);
    root.insert("$id".into(), id.into());
    root.insert("title".into(), title.into());
    root.insert("x-contract-owner".into(), CONTRACT_OWNER.into());
    schema
}

// Schema major 1 globally represents an absent optional value by omitting it.
// MCP `ttl` is the sole nullable field and is required, so it is not rewritten.
fn strip_optional_nulls(schema: &mut Value) {
    if let Some(object) = schema.as_object_mut() {
        let required: Vec<_> = object
            .get("required")
            .and_then(Value::as_array)
            .into_iter()
            .flatten()
            .filter_map(Value::as_str)
            .map(str::to_owned)
            .collect();
        if let Some(properties) = object.get_mut("properties").and_then(Value::as_object_mut) {
            for (name, property) in properties {
                if !required.iter().any(|required| required == name) {
                    remove_null_variant(property);
                }
            }
        }
        for value in object.values_mut() {
            strip_optional_nulls(value);
        }
    } else if let Some(array) = schema.as_array_mut() {
        for value in array {
            strip_optional_nulls(value);
        }
    }
}

fn remove_null_variant(schema: &mut Value) {
    if let Some(types) = schema.get_mut("type").and_then(Value::as_array_mut) {
        types.retain(|kind| kind != "null");
    }
    for keyword in ["anyOf", "oneOf"] {
        if let Some(variants) = schema.get_mut(keyword).and_then(Value::as_array_mut) {
            variants.retain(|variant| variant.get("type") != Some(&json!("null")));
        }
    }
}

fn object_mut(value: &mut Value) -> &mut Map<String, Value> {
    value
        .as_object_mut()
        .expect("contract schemas are JSON objects")
}

/// Walks a generated schema through existing object properties only.
///
/// `schemars` owns the `$defs` layout, so a renamed or reshaped definition
/// must fail loudly here instead of fabricating a null placeholder through
/// `Value`'s `IndexMut` and silently emitting an invalid schema.
fn generated_path_mut<'a>(mut schema: &'a mut Value, segments: &[&str]) -> &'a mut Value {
    for segment in segments {
        schema = object_mut(schema)
            .get_mut(*segment)
            .unwrap_or_else(|| panic!("generated schema is missing the {segment} property"));
    }
    schema
}

fn property_mut<'a>(schema: &'a mut Value, property: &str) -> &'a mut Map<String, Value> {
    schema["properties"][property]
        .as_object_mut()
        .expect("derived property schema is an object")
}

fn set_const(schema: &mut Value, property: &str, value: Value) {
    let property = property_mut(schema, property);
    property.clear();
    property.insert("const".into(), value);
}

fn set_pattern(schema: &mut Value, property: &str, pattern: &str) {
    property_mut(schema, property).insert("pattern".into(), pattern.into());
}

fn config_schema() -> Value {
    let mut schema = root_schema::<schema_types::Config>(
        "https://pangram.micr.dev/schemas/config-v1.json",
        "Pangram CLI configuration v1",
    );
    set_const(&mut schema, "config_version", json!(1));
    set_default(
        &mut schema,
        &["$defs", "HistoryConfig", "properties", "enabled"],
        json!(false),
    );
    set_default(
        &mut schema,
        &["$defs", "TuiConfig", "properties", "intro"],
        json!("once"),
    );
    set_default(
        &mut schema,
        &["$defs", "TuiConfig", "properties", "keymap"],
        json!("regular"),
    );
    set_default(
        &mut schema,
        &["$defs", "TuiConfig", "properties", "motion"],
        json!("full"),
    );
    let rate = object_mut(generated_path_mut(
        &mut schema,
        &[
            "$defs",
            "NetworkConfig",
            "properties",
            "max_requests_per_second",
        ],
    ));
    rate.remove("minimum");
    rate.insert("exclusiveMinimum".into(), json!(0));
    rate.insert("default".into(), json!(5));
    schema
}

fn set_default(schema: &mut Value, segments: &[&str], value: Value) {
    object_mut(generated_path_mut(schema, segments)).insert("default".into(), value);
}

fn tui_state_schema() -> Value {
    let mut schema = root_schema::<schema_types::TuiState>(
        "https://pangram.micr.dev/schemas/tui-state-v1.json",
        "Pangram CLI TUI state v1",
    );
    set_const(&mut schema, "schema_version", json!("1"));
    set_const(&mut schema, "intro_seen", json!(true));
    schema
}

fn update_manifest_schema() -> Value {
    let mut schema = root_schema::<schema_types::UpdateManifest>(
        "https://pangram.micr.dev/schemas/update-manifest-v1.json",
        "Pangram CLI signed update manifest v1",
    );
    set_const(&mut schema, "schema_version", json!("1"));
    set_const(&mut schema, "channel", json!("stable"));
    set_pattern(&mut schema, "published_at", "Z$");
    schema
}

fn manifest_signature_schema() -> Value {
    let mut schema = root_schema::<schema_types::ManifestSignature>(
        "https://pangram.micr.dev/schemas/manifest-signature-v1.json",
        "Pangram update manifest detached signature v1",
    );
    set_const(&mut schema, "schema_version", json!("1"));
    set_const(&mut schema, "algorithm", json!("ed25519"));
    property_mut(&mut schema, "signature").insert("contentEncoding".into(), "base64".into());
    schema
}

fn update_state_schema() -> Value {
    let mut schema = root_schema::<schema_types::UpdateState>(
        "https://pangram.micr.dev/schemas/update-state-v1.json",
        "Pangram local update-check state v1",
    );
    set_const(&mut schema, "schema_version", json!("1"));
    set_pattern(&mut schema, "last_checked_at", "Z$");
    schema
}

fn install_receipt_schema() -> Value {
    let mut schema = root_schema::<schema_types::InstallReceipt>(
        "https://pangram.micr.dev/schemas/install-receipt-v1.json",
        "Pangram direct-install receipt v1",
    );
    set_const(&mut schema, "schema_version", json!("1"));
    set_const(&mut schema, "method", json!("direct"));
    set_pattern(&mut schema, "installed_at", "Z$");
    schema
}

fn cli_reference() -> Value {
    let mut value =
        serde_json::to_value(FULL_GRAMMAR).expect("the static CLI grammar always serializes");
    let root = object_mut(&mut value);
    root.insert("$schema".into(), DRAFT_2020_12.into());
    root.insert(
        "$id".into(),
        "https://pangram.micr.dev/generated/cli-reference-v1.json".into(),
    );
    root.insert("title".into(), "Pangram CLI grammar reference v1".into());
    root.insert("x-contract-owner".into(), CONTRACT_OWNER.into());
    value
}

fn error_reference() -> Value {
    let errors: Vec<_> = ErrorCode::ALL
        .iter()
        .map(|code| {
            json!({
                "code": code.as_str(),
                "category": code.category().as_str(),
                "default_retryable": code.default_retryable(),
                "contextual_retryability": code.retryability_is_contextual(),
            })
        })
        .collect();
    let exits: Vec<_> = ExitCode::ALL
        .iter()
        .map(|code| json!({"code": code.as_u8()}))
        .collect();
    json!({
        "$schema": DRAFT_2020_12,
        "$id": "https://pangram.micr.dev/generated/error-reference-v1.json",
        "x-contract-owner": CONTRACT_OWNER,
        "title": "Pangram CLI error and exit-code reference v1",
        "schema_version": "1",
        "errors": errors,
        "exit_codes": exits,
    })
}

// The output schema combines Schemars-owned definitions with cross-field JSON
// Schema constraints which Rust's type system cannot express by derivation.
fn output_schema() -> Value {
    let mut registry = rust_schema::<schema_types::OutputRegistry>();
    strip_optional_nulls(&mut registry);
    let mut definitions = object_mut(&mut registry)
        .remove("$defs")
        .expect("the output registry has definitions");

    patch_output_definitions(&mut definitions);
    let analysis = schema_ref::<Analysis<CanonicalError>>();
    let array = json!({"type": "array", "minItems": 1, "items": analysis});
    let conditions = vec![
        data_condition(
            &["detect", "plagiarism", "analyze"],
            json!({"oneOf": [analysis, array]}),
        ),
        data_condition(
            &["task_status", "task_wait", "history_show", "history_rerun"],
            schema_ref::<Analysis<CanonicalError>>(),
        ),
        data_condition(
            &["bulk_submit"],
            json!({"oneOf": [
                schema_ref::<BulkCollection>(),
                schema_ref::<crate::output::BulkDryRun>(),
            ]}),
        ),
        data_condition(
            &["bulk_status", "bulk_wait"],
            schema_ref::<BulkCollection>(),
        ),
        data_condition(&["bulk_results"], schema_ref::<BulkPage<CanonicalError>>()),
        data_condition(
            &["history_list", "history_search"],
            schema_ref::<AnalysisPage<CanonicalError>>(),
        ),
        data_condition(
            &[
                "history_delete",
                "history_clear",
                "auth_set",
                "auth_logout",
                "config_set",
                "mcp_install",
                "mcp_uninstall",
            ],
            schema_ref::<crate::output::MutationAcknowledgement>(),
        ),
        data_condition(&["auth_status"], schema_ref::<crate::output::AuthStatus>()),
        data_condition(
            &["config_list"],
            schema_ref::<crate::output::ConfigListStatus>(),
        ),
        data_condition(
            &["config_get"],
            schema_ref::<crate::output::ConfigGetStatus>(),
        ),
        data_condition(
            &["config_path"],
            schema_ref::<crate::output::ConfigPathStatus>(),
        ),
        data_condition(&["doctor"], schema_ref::<crate::output::DoctorStatus>()),
        data_condition(&["mcp_status"], schema_ref::<crate::output::McpStatus>()),
        data_condition(
            &["update_check", "update_install"],
            schema_ref::<crate::output::UpdateStatus>(),
        ),
    ];
    let json_commands: Vec<_> = ResolvedCommand::ALL
        .iter()
        .copied()
        .filter(|command| command.uses_json_envelope())
        .map(ResolvedCommand::as_str)
        .collect();
    let all_commands: Vec<_> = ResolvedCommand::ALL
        .iter()
        .copied()
        .map(ResolvedCommand::as_str)
        .collect();

    let definitions = object_mut(&mut definitions);
    definitions.insert(
        "successEnvelope".into(),
        json!({
            "type": "object",
            "required": ["schema_version", "command", "data", "meta"],
            "properties": {
                "schema_version": {"const": "1"},
                "command": {"enum": json_commands},
                "data": {"oneOf": [{"type": "object"}, {"type": "array"}]},
                "meta": schema_ref::<EnvelopeMeta>(),
            },
            "allOf": conditions,
            "not": {"required": ["error"]},
            "additionalProperties": true,
        }),
    );
    definitions.insert(
        "errorEnvelope".into(),
        json!({
            "type": "object",
            "required": ["schema_version", "command", "error", "meta"],
            "properties": {
                "schema_version": {"const": "1"},
                "command": {"enum": all_commands},
                "error": schema_ref::<CanonicalError>(),
                "meta": schema_ref::<EnvelopeMeta>(),
            },
            "not": {"required": ["data"]},
            "additionalProperties": true,
        }),
    );

    json!({
        "$schema": DRAFT_2020_12,
        "$id": "https://pangram.micr.dev/schemas/output-v1.json",
        "x-contract-owner": CONTRACT_OWNER,
        "title": "Pangram CLI output envelope v1",
        "oneOf": [
            {"$ref": "#/$defs/successEnvelope"},
            {"$ref": "#/$defs/errorEnvelope"}
        ],
        "$defs": definitions,
    })
}

fn schema_ref<T: JsonSchema>() -> Value {
    json!({"$ref": format!("#/$defs/{}", T::schema_name())})
}

fn data_condition(commands: &[&str], data: Value) -> Value {
    let command = if commands.len() == 1 {
        json!({"const": commands[0]})
    } else {
        json!({"enum": commands})
    };
    json!({
        "if": {"properties": {"command": command}, "required": ["command"]},
        "then": {"properties": {"data": data}},
    })
}

fn definition_mut<T: JsonSchema>(definitions: &mut Value) -> &mut Value {
    &mut definitions[T::schema_name().as_ref()]
}

fn patch_output_definitions(definitions: &mut Value) {
    if let Some(timestamp) = definitions.get_mut("UtcTimestamp") {
        object_mut(timestamp).insert("pattern".into(), "Z$".into());
    }

    // Internally tagged Serde enums ignore known fields from other variants.
    // Keep the schema strict even though those variants share open objects.
    // Fail loudly if schemars renames the generic instantiations so a silent
    // no-op cannot drop the exclusivity constraint from the emitted schema.
    let check_state_invariant = json!({"oneOf": state_payload_invariant("result")});
    let mut patched = 0_usize;
    for (name, definition) in object_mut(definitions).iter_mut() {
        if name.starts_with("CheckState") {
            object_mut(definition).insert("allOf".into(), json!([check_state_invariant]));
            patched += 1;
        }
    }
    assert_eq!(
        patched, 2,
        "expected the AI-detection and plagiarism check-state definitions to be patched"
    );

    let checks = definition_mut::<OrderedChecks<Check<CanonicalError>>>(definitions);
    object_mut(checks).insert(
        "allOf".into(),
        json!([{
            "if": {"minItems": 2},
            "then": {
                "prefixItems": [
                    {"properties": {"kind": {"const": "ai_detection"}}, "required": ["kind"]},
                    {"properties": {"kind": {"const": "plagiarism"}}, "required": ["kind"]}
                ]
            }
        }]),
    );
    let analysis = definition_mut::<Analysis<CanonicalError>>(definitions);
    object_mut(analysis).insert("not".into(), json!({"required": ["retry_of", "rerun_of"]}));
    // Constrain the derived analysis schema to a single object. The
    // Schemars-derived definition also validates against bare array items in
    // some envelopes, which would make the multi-form object-versus-array
    // `oneOf` ambiguous.
    push_all_of(analysis, json!({"type": "object"}));
    // Encode the documented parent-status derivation so schema consumers agree
    // with the canonical `Analysis` deserializer (PR #14 review d).
    push_all_of(analysis, parent_status_invariant());
    push_all_of(
        analysis,
        when_not_submitted(json!({
            "properties": {
                "checks": {
                    "not": {
                        "contains": {
                            "properties": {
                                "upstream": {
                                    "type": "object",
                                    "required": ["task_id"]
                                }
                            },
                            "required": ["upstream"]
                        }
                    }
                },
                "provenance": {
                    "not": {
                        "anyOf": [
                            {"required": ["upstream_task_ids"]},
                            {"required": ["upstream_bulk_id"]},
                            {"required": ["submitted_at"]},
                            {"required": ["completed_at"]}
                        ]
                    }
                }
            }
        })),
    );
    // Encode the documented bulk status/counter relationships that Draft
    // 2020-12 can express, so schema consumers agree with the canonical
    // `BulkCollection` constructor. The cross-field arithmetic bounds and the
    // exact terminal equation remain constructor-owned; see
    // `bulk_status_invariants` (PR #14 review d).
    let bulk_collection = definition_mut::<BulkCollection>(definitions);
    for invariant in bulk_status_invariants() {
        push_all_of(bulk_collection, invariant);
    }
    push_all_of(
        bulk_collection,
        when_not_submitted(json!({
            "properties": {
                "accepted": {"const": 0},
                "succeeded": {"const": 0},
                "failed": {"const": 0}
            },
            "not": {"required": ["upstream_bulk_id"]}
        })),
    );
    // An accepted submission must have returned an upstream bulk identifier.
    push_all_of(
        bulk_collection,
        json!({
            "if": {
                "properties": {"submission_outcome": {"const": "accepted"}},
                "required": ["submission_outcome"]
            },
            "then": {"required": ["upstream_bulk_id"]}
        }),
    );
    // A terminally resolved submission cannot still report active statuses.
    push_all_of(
        bulk_collection,
        json!({
            "if": {
                "properties": {"submission_outcome": {"const": "terminal"}},
                "required": ["submission_outcome"]
            },
            "then": {"properties": {"status": {"enum": ["succeeded", "failed", "partial"]}}}
        }),
    );
    let bulk_item = definition_mut::<BulkItem<CanonicalError>>(definitions);
    let properties = object_mut(&mut bulk_item["properties"]);
    let mut status = rust_schema::<CheckStatus>();
    object_mut(&mut status).remove("$schema");
    object_mut(&mut status).remove("title");
    properties.insert("status".into(), status);
    properties.insert("analysis".into(), schema_ref::<Analysis<CanonicalError>>());
    properties.insert("error".into(), schema_ref::<CanonicalError>());
    bulk_item["required"]
        .as_array_mut()
        .expect("BulkItem required fields are an array")
        .push(json!("status"));
    object_mut(bulk_item).insert("oneOf".into(), state_payload_invariant("analysis"));
    push_all_of(
        bulk_item,
        json!({
            "if": {
                "properties": {
                    "status": {"enum": ["queued", "succeeded"]}
                },
                "required": ["status"]
            },
            "then": {
                "not": {"required": ["last_stage"]}
            }
        }),
    );

    let unknown_submission = definition_mut::<SubmissionOutcomeUnknownDetails>(definitions);
    let properties = object_mut(&mut unknown_submission["properties"]);
    properties.insert(
        "analysis_id".into(),
        schema_ref::<crate::domain::AnalysisId>(),
    );
    properties.insert("bulk_id".into(), schema_ref::<crate::domain::BulkId>());
    object_mut(unknown_submission).insert("additionalProperties".into(), json!(false));

    let error = definition_mut::<CanonicalError>(definitions);
    property_mut(error, "message").insert("minLength".into(), json!(1));
    object_mut(error).insert(
        "allOf".into(),
        json!([
            error_category_invariant(),
            error_retry_invariant(),
            {
                "if": {"properties": {"code": {"const": "submission_outcome_unknown"}}},
                "then": {
                    "properties": {
                        "retryable": {"const": false},
                        "details": schema_ref::<SubmissionOutcomeUnknownDetails>(),
                        "recovery": {
                            "type": "object",
                            "properties": {
                                "message": {
                                    "const": SUBMISSION_OUTCOME_UNKNOWN_RECOVERY_MESSAGE
                                }
                            },
                            "required": ["message"],
                            "additionalProperties": false
                        }
                    },
                    "required": ["details", "recovery"]
                }
            }
        ]),
    );
}

fn push_all_of(schema: &mut Value, invariant: Value) {
    object_mut(schema)
        .entry("allOf")
        .or_insert_with(|| json!([]))
        .as_array_mut()
        .expect("allOf is an array")
        .push(invariant);
}

// The parent-status derivation depends only on the set of check statuses, not
// their positions, so the schema constrains the multiset with `contains`,
// `not contains`, and `items` rather than addressing array indices. Every
// clause is forward implications: each of the five statuses reaches exactly
// the check-status sets that the canonical `derive_parent_status` maps to it,
// and every other status fails its own clause for those sets.
fn checks_contain_status(status: &str) -> Value {
    json!({
        "contains": {
            "properties": {"status": {"const": status}},
            "required": ["status"]
        }
    })
}

fn checks_lack_status(status: &str) -> Value {
    json!({"not": checks_contain_status(status)})
}

fn checks_all_status(status: &str) -> Value {
    json!({
        "items": {
            "properties": {"status": {"enum": [status]}}
        }
    })
}

fn parent_status_case(status: &str, checks: Value) -> Value {
    json!({
        "if": {
            "properties": {"status": {"const": status}},
            "required": ["status"]
        },
        "then": {"properties": {"checks": checks}}
    })
}

/// The documented parent-status derivation from contracts.md section 4.1,
/// encoded as one `if status ... then checks ...` implication per status. The
/// five conditions mirror `derive_parent_status`:
///
/// - `running`: some check is `running`
/// - `queued`: no `running` check and some check is `queued`
/// - `succeeded`: no `running` or `queued` check and every check is `succeeded`
/// - `failed`: no `running` or `queued` check and every check is `failed`
/// - `partial`: no `running` or `queued` check with both a `succeeded` and a
///   `failed` check
///
/// Because every non-empty set of one or two check statuses derives exactly one
/// parent status, a declared status that disagrees triggers its own `then` and
/// fails; the matching status passes. No separate reverse implication is
/// required.
fn parent_status_invariant() -> Value {
    json!({
        "allOf": [
            parent_status_case("running", checks_contain_status("running")),
            parent_status_case(
                "queued",
                json!({"allOf": [checks_lack_status("running"), checks_contain_status("queued")]})
            ),
            parent_status_case(
                "succeeded",
                json!({"allOf": [
                    checks_lack_status("running"),
                    checks_lack_status("queued"),
                    checks_all_status("succeeded")
                ]})
            ),
            parent_status_case(
                "failed",
                json!({"allOf": [
                    checks_lack_status("running"),
                    checks_lack_status("queued"),
                    checks_all_status("failed")
                ]})
            ),
            parent_status_case(
                "partial",
                json!({"allOf": [
                    checks_lack_status("running"),
                    checks_lack_status("queued"),
                    checks_contain_status("succeeded"),
                    checks_contain_status("failed")
                ]})
            )
        ]
    })
}

/// The bulk status/counter relationships that Draft 2020-12 can express with
/// standard keywords: keyword-level counter minimums and zero-pins tied to the
/// collection `status`. The cross-field arithmetic bounds and the exact
/// terminal equation (`accepted <= total_items`, `succeeded <= accepted`,
/// `succeeded + failed <= total_items`, terminal `succeeded + failed =
/// total_items`) compare or sum distinct integer fields; no standard keyword
/// expresses those over unbounded integers, so the canonical
/// `BulkCounters`/`BulkCollection` constructor remains authoritative for them
/// (see contracts.md section 9 and docs/update-contract.md, which delegates
/// non-expressible invariants to the Rust type). `failed` includes immediate
/// upstream rejection, so `succeeded + failed` may exceed `accepted`; there is
/// intentionally no `succeeded + failed <= accepted` clause (PR #14 review d).
fn bulk_status_invariants() -> Vec<Value> {
    vec![
        // A `succeeded` collection finished every item successfully, so no
        // item failed and at least one succeeded (`total_items >= 1`).
        json!({
            "if": {"properties": {"status": {"const": "succeeded"}}, "required": ["status"]},
            "then": {"properties": {"failed": {"const": 0}, "succeeded": {"minimum": 1}}}
        }),
        // A `failed` collection finished every item unsuccessfully, so no item
        // succeeded and at least one failed.
        json!({
            "if": {"properties": {"status": {"const": "failed"}}, "required": ["status"]},
            "then": {"properties": {"succeeded": {"const": 0}, "failed": {"minimum": 1}}}
        }),
        // A `partial` collection finished every item with both outcomes, so
        // both terminal counters are positive.
        json!({
            "if": {"properties": {"status": {"const": "partial"}}, "required": ["status"]},
            "then": {"properties": {"succeeded": {"minimum": 1}, "failed": {"minimum": 1}}}
        }),
    ]
}

fn when_not_submitted(then: Value) -> Value {
    json!({
        "if": {
            "properties": {"submission_outcome": {"const": "not_submitted"}},
            "required": ["submission_outcome"]
        },
        "then": then
    })
}

fn state_payload_invariant(success_field: &str) -> Value {
    json!([
        {
            "properties": {"status": {"enum": ["queued", "running"]}},
            "not": {"anyOf": [{"required": [success_field]}, {"required": ["error"]}]}
        },
        {
            "properties": {"status": {"const": "succeeded"}},
            "required": [success_field],
            "not": {"required": ["error"]}
        },
        {
            "properties": {"status": {"const": "failed"}},
            "required": ["error"],
            "not": {"required": [success_field]}
        }
    ])
}

fn error_category_invariant() -> Value {
    let mut categories: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    for code in ErrorCode::ALL {
        categories
            .entry(code.category().as_str())
            .or_default()
            .push(code.as_str());
    }
    let variants: Vec<_> = categories
        .into_iter()
        .map(|(category, codes)| {
            json!({
                "properties": {
                    "code": {"enum": codes},
                    "category": {"const": category}
                }
            })
        })
        .collect();
    json!({"oneOf": variants})
}

fn error_retry_invariant() -> Value {
    let retryable: Vec<_> = ErrorCode::ALL
        .iter()
        .filter(|code| code.default_retryable())
        .map(|code| code.as_str())
        .collect();
    let fixed_non_retryable: Vec<_> = ErrorCode::ALL
        .iter()
        .filter(|code| !code.default_retryable() && !code.retryability_is_contextual())
        .map(|code| code.as_str())
        .collect();
    json!({
        "allOf": [
            {
                "if": {"properties": {"code": {"enum": retryable}}},
                "then": {"properties": {"retryable": {"const": true}}}
            },
            {
                "if": {"properties": {"code": {"enum": fixed_non_retryable}}},
                "then": {"properties": {"retryable": {"const": false}}}
            }
        ]
    })
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::generated_path_mut;

    // A renamed or reshaped `$defs` entry must panic instead of fabricating a
    // null placeholder through `Value`'s `IndexMut` (PR #14 review b).
    #[test]
    #[should_panic(expected = "generated schema is missing the TuiConfig property")]
    fn generated_schema_paths_fail_loudly_instead_of_fabricating_nulls() {
        let mut schema = json!({"$defs": {}});
        generated_path_mut(&mut schema, &["$defs", "TuiConfig", "properties", "intro"]);
    }

    #[test]
    fn generated_schema_paths_resolve_existing_objects() {
        let mut schema = json!({"$defs": {"TuiConfig": {"properties": {}}}});
        let intro = generated_path_mut(&mut schema, &["$defs", "TuiConfig", "properties"]);
        intro
            .as_object_mut()
            .unwrap()
            .insert("intro".into(), json!({"default": "once"}));
        assert_eq!(
            schema["$defs"]["TuiConfig"]["properties"]["intro"],
            json!({"default": "once"})
        );
    }
}
